/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DataTypes.DataCliente;
import Interface.Fabrica;
import Interface.IControladorClientes;
import java.awt.Component;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author gonza
 */
public class ClienteInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClienteInfo
     */
    public ClienteInfo() {
        initComponents();
        this.modo = "AltaCliente";
        this.setTitle("Alta Cliente");
        this.jButtonAceptar.setText("Crear Cliente");
    }
    
    public ClienteInfo(String modo, int idCliente) {
        initComponents();
        
        this.modo = modo;
        
        if (this.modo.equals("ConsultarCliente")){
            this.jButtonAceptar.setText("Aceptar");
            this.jButtonCancelar.setText("Cerrar");
            this.setTitle("Consultar Cliente");
        } else if (this.modo.equals("ModificarCliente")){
            this.jButtonAceptar.setText("Modificar Cliente");
            this.setTitle("Modificar Cliente");
        }
        
        try{
            this.crearFormularioDesdeDataCliente(idCliente);
            
            if (this.modo.equals("ModificarCliente")){
                // Nada
            } else if (this.modo.equals("ConsultarCliente")){
                // Inhabilito los text inputs
                this.jTextFieldNombreCliente.setEditable(false);
                this.jTextFieldApellidoCliente.setEditable(false);
                this.jTextFieldTelefonoCliente.setEditable(false);
                this.jTextFieldCelularCliente.setEditable(false);
                this.jTextFieldEmailCliente.setEditable(false);
                this.jTextFieldDireccionCliente.setEditable(false);
                this.jTextAreaInfoAdicionalCliente.setEditable(false);
            }
        }
        catch (Exception exc){
            JOptionPane.showMessageDialog(this, exc.getMessage(),"Error",0);
            JDesktopPane desktopPane = this.getDesktopPane();
            desktopPane.remove(this);
            desktopPane.updateUI();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInfoAdicionalCliente = new javax.swing.JTextArea();
        jTextFieldApellidoCliente = new javax.swing.JTextField();
        jTextFieldTelefonoCliente = new javax.swing.JTextField();
        jTextFieldCelularCliente = new javax.swing.JTextField();
        jTextFieldEmailCliente = new javax.swing.JTextField();
        jTextFieldDireccionCliente = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setTitle("Alta Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Cliente"));

        jTextFieldNombreCliente.setColumns(20);
        jTextFieldNombreCliente.setNextFocusableComponent(jTextFieldApellidoCliente);

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Apellido: ");

        jLabel3.setText("Email: ");

        jLabel4.setText("Telefono: ");

        jLabel5.setText("Celular: ");

        jLabel6.setText("Direccion: ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion Adicional", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jTextAreaInfoAdicionalCliente.setColumns(20);
        jTextAreaInfoAdicionalCliente.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInfoAdicionalCliente);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextFieldApellidoCliente.setColumns(20);

        jTextFieldTelefonoCliente.setColumns(20);

        jTextFieldCelularCliente.setColumns(20);

        jTextFieldEmailCliente.setColumns(20);

        jTextFieldDireccionCliente.setColumns(20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jButtonAceptar.setText("Alta Cliente");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // Eliminarse del jDesktopPane
        JDesktopPane desktopPane =  this.getDesktopPane();
        desktopPane.remove(this);
        desktopPane.updateUI();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        Fabrica fab = new Fabrica();
        IControladorClientes icc = fab.getIControladorClientes();
        
        if (this.modo.equals("ConsultarCliente")){
            // Cierro la ventana
            JDesktopPane desktopPane = this.getDesktopPane();
            desktopPane.remove(this);
            desktopPane.updateUI();
        } else if (this.modo.equals("AltaCliente") || this.modo.equals("ModificarCliente")){
            DataCliente dataC;
            try{
                dataC = this.crearDataClienteDesdeFormulario();
            }
            catch(Exception exc){
                JOptionPane.showMessageDialog(this, exc.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (this.modo.equals("AltaCliente")){
                int respuesta;
                respuesta = JOptionPane.showConfirmDialog(this, "Esta seguro que desea crear el cliente?", "Crear Cliente", 0);
                if (respuesta == JOptionPane.YES_OPTION){
                    // Quiere crear el cliente
                    try{
                        icc.altaCliente(dataC);
                        JOptionPane.showMessageDialog(this, "Cliente creado con exito","Exito",JOptionPane.INFORMATION_MESSAGE);
                        JDesktopPane desktopPane = this.getDesktopPane();
                        desktopPane.remove(this);
                        desktopPane.updateUI();
                    }
                    catch (Exception exc){
                        JOptionPane.showMessageDialog(this, exc.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                    }
                } else if (respuesta == JOptionPane.NO_OPTION){
                    // No lo quiere crear, no hago nada
                    JOptionPane.showMessageDialog(this, "No se ha creado el cliente","Info",JOptionPane.INFORMATION_MESSAGE);
                }

            } else if (this.modo.equals("ModificarCliente")){
                dataC.setId(this.dataCliente.getId());

                int respuesta;
                respuesta = JOptionPane.showConfirmDialog(this, "Esta seguro que desea modificar el cliente?", "Modificar Cliente", 0);
                if (respuesta == JOptionPane.YES_OPTION){
                    // Quiere modificar el cliente
                    JDesktopPane desktopPane = this.getDesktopPane();
                    try{
                        icc.modificarCliente(dataC);
                        JOptionPane.showMessageDialog(this, "Cliente modificado con exito","Exito",JOptionPane.INFORMATION_MESSAGE);
                        desktopPane.remove(this);
                        desktopPane.updateUI();
                    }
                    catch (Exception exc){
                        JOptionPane.showMessageDialog(this, exc.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
                    }
                    
                    Component[] ventanas = desktopPane.getComponents();
                    ClienteLista ventanaListaClientes = null;
                    for(Component comp: ventanas){
                        if (comp instanceof ClienteLista){
                            ventanaListaClientes = (ClienteLista)comp;
                            break;
                        }
                    }
                    if (ventanaListaClientes != null)
                        ventanaListaClientes.actualizarTablaClientes();
                    
                } else if (respuesta == JOptionPane.NO_OPTION){
                    // No lo quiere modificar
                    JOptionPane.showMessageDialog(this, "No se ha modificado el cliente","Info",0);
                }

            }  
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void crearFormularioDesdeDataCliente(int idCliente) throws Exception{
        Fabrica fab = new Fabrica();
        IControladorClientes icc = fab.getIControladorClientes();
        DataCliente dc;
        
        try{
            dc = icc.obtenerCliente(idCliente);
        
            if (this.modo.equals("ModificarCliente"))
                this.dataCliente = dc;
            
            this.jTextFieldNombreCliente.setText(dc.getNombre());
            this.jTextFieldApellidoCliente.setText(dc.getApellido());
            this.jTextFieldTelefonoCliente.setText(dc.getTelefono());
            this.jTextFieldCelularCliente.setText(dc.getCelular());
            this.jTextFieldEmailCliente.setText(dc.getEmail());
            this.jTextFieldDireccionCliente.setText(dc.getDireccion());
            this.jTextAreaInfoAdicionalCliente.setText(dc.getInf_adicional());
        }
        catch(Exception exc){
            throw new Exception("Error creando el formulario");
        }
    }
    
    private DataCliente crearDataClienteDesdeFormulario() throws Exception{
        DataCliente dataC = new DataCliente();
        if (this.jTextFieldNombreCliente.getText().equals(""))
            throw new Exception("Debe ingresar un nombre");
            
        dataC.setNombre(this.jTextFieldNombreCliente.getText());
        dataC.setApellido(this.jTextFieldApellidoCliente.getText());
        dataC.setTelefono(this.jTextFieldTelefonoCliente.getText());
        dataC.setCelular(this.jTextFieldCelularCliente.getText());
        dataC.setEmail(this.jTextFieldEmailCliente.getText());
        dataC.setDireccion(this.jTextFieldDireccionCliente.getText());
        dataC.setInf_adicional(this.jTextAreaInfoAdicionalCliente.getText());
        return dataC;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInfoAdicionalCliente;
    private javax.swing.JTextField jTextFieldApellidoCliente;
    private javax.swing.JTextField jTextFieldCelularCliente;
    private javax.swing.JTextField jTextFieldDireccionCliente;
    private javax.swing.JTextField jTextFieldEmailCliente;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldTelefonoCliente;
    // End of variables declaration//GEN-END:variables
    
    // modo = "AltaCliente" | "ConsultarCliente" | "ModificarCliente"
    private String modo;
    // DataCliente, si estamos modificando el cliente
    private DataCliente dataCliente;

}
