/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VisorImg.java
 *
 * Created on 11/04/2012, 12:52:23 AM
 */

package Formularios;

import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Santiago
 */
public class VisorImg extends javax.swing.JInternalFrame {

    /** Creates new form VisorImg */
    public VisorImg(String path) {

        initComponents();
    try{
        ImageIcon image = new ImageIcon(path);
        //ImageIcon imageScalada = new ImageIcon(image.getImage().getScaledInstance(this.jLabel1.getWidth(), this.jLabel1.getHeight(), 1));
        this.jLabel1.setIcon(image);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
